[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "55366b2553d2051232356dc4ac378294f2daa0fa"
lazy = true
os = "windows"

    [[CairoMakie.download]]
    sha256 = "24f39a6ea4c75f2a1745279e038db18485d598f6c7606a034bb60699fb52e40e"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.2/CairoMakie-windows-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "a15ee1f31cd970621fbe73a9a9824489d66717b5"
lazy = true
os = "macos"

    [[CairoMakie.download]]
    sha256 = "4cf9ab321e2b2d8d355c8583536d3de3ff81976f86086f32813e086dd1f14d48"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.2/CairoMakie-macOS-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "02252791ecb6c1279b4e2f39645138f9b9136d54"
lazy = true
libc = "glibc"
os = "linux"

    [[CairoMakie.download]]
    sha256 = "4ec7c42237cf2bc538b83454afa467bdb9746c07bc1b88cae47082952e247c2e"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.2/CairoMakie-ubuntu-latest-x64-1.7.tar.gz"

[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "180234eef5c928359d23e4036cff8cf769990110"
lazy = true
os = "windows"

    [[DataFrames.download]]
    sha256 = "952491cea3e64ea605c27aaf9267adb2fd0a05db3bd778ecc54755ed408309e2"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.2/DataFrames-windows-latest-x64-1.7.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "6cfee6ab8c4ca762cdc0311793ea185bea59fa9a"
lazy = true
os = "macos"

    [[DataFrames.download]]
    sha256 = "2b903ab7124f36ca58ab0945e16255314ea96eadbd6b529530b7ce971063400f"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.2/DataFrames-macOS-latest-x64-1.7.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "29ab45abc59cfc9f9886c52110b0901164b0bbf6"
lazy = true
libc = "glibc"
os = "linux"

    [[DataFrames.download]]
    sha256 = "ca92fb8994a01d95c2429431be09fbf13fe76eedf685fe8418ad9585b5078c03"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.2/DataFrames-ubuntu-latest-x64-1.7.tar.gz"
