[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "d93df1e6827d889dab493acc9c3adffcb9ec840e"
lazy = true
os = "windows"

    [[CairoMakie.download]]
    sha256 = "db85f7caae5b05a1cf151b5a4d6472fdb6f1c19a01f1b3f6e0e57a698bcc6b86"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/CairoMakie-windows-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "5c78ae73c89134b49f0c8753128d8b881db6f4f6"
lazy = true
os = "macos"

    [[CairoMakie.download]]
    sha256 = "22b78b25f7851bd3037fff4349dc3158ae8542172b28b6ccf18dd663611afb71"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/CairoMakie-macOS-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "8a1206381b8e6889ebee0688fe4c5f00606c1a98"
lazy = true
libc = "glibc"
os = "linux"

    [[CairoMakie.download]]
    sha256 = "bb33a930574fb7fe70e86122d089f53787e8f389407ab5de78ef3a97b235de4c"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/CairoMakie-ubuntu-latest-x64-1.7.tar.gz"

[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "e307744a9a1166b1ded1a3c5ee921603c3de2c9d"
lazy = true
os = "windows"

    [[DataFrames.download]]
    sha256 = "0933a21718f08434d75caaaa07f9e48c164a15f3493c95fe43ecf04858885dc3"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/DataFrames-windows-latest-x64-1.7.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "ff86517df95137d2c645db5769cb694dcd8c3d9d"
lazy = true
os = "macos"

    [[DataFrames.download]]
    sha256 = "04432f339832cc511a8aae2df9eefcffccf449c1258f9b2927960e5c09e320d1"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/DataFrames-macOS-latest-x64-1.7.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "8b8177a5ad41084fab58b705140614836a569457"
lazy = true
libc = "glibc"
os = "linux"

    [[DataFrames.download]]
    sha256 = "669b67ae0864914c8000fc35720a40969342cb34ef799a9e79cba7981c6db666"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/DataFrames-ubuntu-latest-x64-1.7.tar.gz"

[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "904af30e4529a3d6d3e48f3ed9b54e976559f545"
lazy = true
os = "windows"

    [[JuliaSyntax.download]]
    sha256 = "2aaab8198145458c3a627c2a139b131448ff0c2382fcbc5c0847286ae0c32654"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/JuliaSyntax-windows-latest-x64-1.7.tar.gz"
[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "413b57cbc507b82885bd52daa22a1b3c426ca4a0"
lazy = true
os = "macos"

    [[JuliaSyntax.download]]
    sha256 = "3d410b06917619f08c250cb3c93a0712f67a82580d3386c8762f262550e2a3b5"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/JuliaSyntax-macOS-latest-x64-1.7.tar.gz"
[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "48b67f837fd3bf330095657e28d84e271e80b938"
lazy = true
libc = "glibc"
os = "linux"

    [[JuliaSyntax.download]]
    sha256 = "cea4859dee78a3738b793a73754be50b8b11c17587691918b20ff1db1b40f635"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.3/JuliaSyntax-ubuntu-latest-x64-1.7.tar.gz"
