[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "108dd071582170ab00bf434b66ffaec7bfcd2bdd"
lazy = true
os = "windows"

    [[CairoMakie.download]]
    sha256 = "c48a4fe679ae25fe1bab4411b5e182704f0136eb72ec0eece84b91a5fd00eae3"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/CairoMakie-windows-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "daaf64e160201ad50a901e78a05d354a4ebf9d70"
lazy = true
os = "macos"

    [[CairoMakie.download]]
    sha256 = "624ea6bb11ba5ade629e3a7a93f4679cf7b6869b57026851df57f421372a3c44"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/CairoMakie-macOS-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "dac7cd78c2ac8d2f5f1a6008f1a2c3ac32a020ea"
lazy = true
libc = "glibc"
os = "linux"

    [[CairoMakie.download]]
    sha256 = "020345605884940aea9f076723bbda11887960874d45105840e0b890b18bc02d"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/CairoMakie-ubuntu-latest-x64-1.7.tar.gz"

[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "5e480244efa07b199544e67162092bb997ae3baf"
lazy = true
os = "windows"

    [[DataFrames.download]]
    sha256 = "81392ac15f1b9b9ae0ad100594980c6798a79ddc4e3c4a05d0547da15ad2d2d0"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/DataFrames-windows-latest-x64-1.7.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "d6bb37ec5c9855a4e9d3da60d409be1ad65a7e4f"
lazy = true
os = "macos"

    [[DataFrames.download]]
    sha256 = "1835a41889a1d32e9ed29076ca091fa6b8cdeae53da036b6add21de1eb37c6d9"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/DataFrames-macOS-latest-x64-1.7.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "b034ebd7cbb812911daa83a9b4edee5bc3574fea"
lazy = true
libc = "glibc"
os = "linux"

    [[DataFrames.download]]
    sha256 = "262f7a9a6feca3ffc137f953266b42f71b9a5ed8ab691fc8f4e089083f1cdc3b"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/DataFrames-ubuntu-latest-x64-1.7.tar.gz"

[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "e8bb17c20fbad060b5e22623e5b0f4ff9a7a4518"
lazy = true
os = "windows"

    [[JuliaSyntax.download]]
    sha256 = "eaf24fc2b77a98a8cdcdf1b7dc7fbe4865be0797db134dd457a20e72190c64e5"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/JuliaSyntax-windows-latest-x64-1.7.tar.gz"
[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "2717478e2439dea950defab38f362da53edf717c"
lazy = true
os = "macos"

    [[JuliaSyntax.download]]
    sha256 = "e796ab9fe36302b750ac44cf096ef215ef771ef6778b65db8215427f6e1538a4"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/JuliaSyntax-macOS-latest-x64-1.7.tar.gz"
[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "a447b5e009a45d237295a3cea7da41baa7d86dcc"
lazy = true
libc = "glibc"
os = "linux"

    [[JuliaSyntax.download]]
    sha256 = "6506aecf8be4de5fc6b9d2531716d2abe553b5e985b6a584d45d17aa18a212ee"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.5/JuliaSyntax-ubuntu-latest-x64-1.7.tar.gz"
