[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "775eedb6bd1f0c75edbb2528348d57238569da3f"
lazy = true
os = "windows"

    [[CairoMakie.download]]
    sha256 = "0bbc3ca8f5559ab3d8d2da0590ff2d753b46e8651ab489623b1a19b097029112"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.1/CairoMakie-windows-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "e9f83b1241ca98f5d26ee6e849d3fb9218759df9"
lazy = true
os = "macos"

    [[CairoMakie.download]]
    sha256 = "5419f578ac6382fd35c87b8c8dae1f70e151ede8b30fb309e7b276a304dc607f"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.1/CairoMakie-macOS-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "7d8878de845632e417fb674e6b47969f005f4b36"
lazy = true
libc = "glibc"
os = "linux"

    [[CairoMakie.download]]
    sha256 = "acf716f5043703c9fb5816a16c01c23e68de1f7fb3942b677acadd9b1ed523db"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.0.1/CairoMakie-ubuntu-latest-x64-1.7.tar.gz"
