[[AlgebraOfGraphics]]
arch = "x86_64"
git-tree-sha1 = "06c67e79b60a5c264b80a156d81cf66097906483"
lazy = true
os = "windows"

    [[AlgebraOfGraphics.download]]
    sha256 = "24f6013b44a1d122a728317a4912ebd62601ca6c54d1d11d04d90226965b372c"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/AlgebraOfGraphics-windows-latest-x64-1.8.tar.gz"
[[AlgebraOfGraphics]]
arch = "x86_64"
git-tree-sha1 = "7454aa7c066965573e84476c7e0ec829c756a5e6"
lazy = true
os = "macos"

    [[AlgebraOfGraphics.download]]
    sha256 = "69137a4f8920ea5927ae58ebac937ec29146f0a92e2b4adfcc1a959785bb7a83"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/AlgebraOfGraphics-macOS-latest-x64-1.8.tar.gz"
[[AlgebraOfGraphics]]
arch = "x86_64"
git-tree-sha1 = "e248a72f227eedd6c788ac3836d86d995b5a11e8"
lazy = true
libc = "glibc"
os = "linux"

    [[AlgebraOfGraphics.download]]
    sha256 = "d634d25c1d048a47e8231b55d63c3602a895fbc7e7c15a2a56aea8c36e67d48c"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/AlgebraOfGraphics-ubuntu-latest-x64-1.8.tar.gz"

[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "db13548333845f3ba6bcec154bd1a933f1cf84c7"
lazy = true
os = "windows"

    [[DataFrames.download]]
    sha256 = "03f5e1e5ae10cc7988739326794b7f120df51e497636a7a7a9298a037a3afe05"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/DataFrames-windows-latest-x64-1.8.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "c201f49455ae64cde458406802224f7f9d13b5e8"
lazy = true
os = "macos"

    [[DataFrames.download]]
    sha256 = "2c215279277b7dc7eaa0de8d93ce194b2c6a000a907afd09addf386feafb3148"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/DataFrames-macOS-latest-x64-1.8.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "b4ae2c2c4a14e2f4b4d960a714787c33207efad4"
lazy = true
libc = "glibc"
os = "linux"

    [[DataFrames.download]]
    sha256 = "ec8ac1fd776368a77ed6d4910563e5f4b2cef94c854cca5b8732bb45f946c4bd"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/DataFrames-ubuntu-latest-x64-1.8.tar.gz"

[[JuliaFormatter]]
arch = "x86_64"
git-tree-sha1 = "d059ad9312979192591ec02c1eb8aa7948bca0d6"
lazy = true
os = "windows"

    [[JuliaFormatter.download]]
    sha256 = "b8f947c28cf05feac999e04fd82f32e7a983d842bfb70342dd409d5d141e6ddd"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/JuliaFormatter-windows-latest-x64-1.8.tar.gz"
[[JuliaFormatter]]
arch = "x86_64"
git-tree-sha1 = "a2c8e18056b6c6a2cb4f3a467e02dd064152346f"
lazy = true
os = "macos"

    [[JuliaFormatter.download]]
    sha256 = "3522df4ec59558c86593b0bac179b2f0bbb2c69bf4c323e347226d0a0bb562f6"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/JuliaFormatter-macOS-latest-x64-1.8.tar.gz"
[[JuliaFormatter]]
arch = "x86_64"
git-tree-sha1 = "b0f516a8abb6df6a1ee538107bb7b118d75b7780"
lazy = true
libc = "glibc"
os = "linux"

    [[JuliaFormatter.download]]
    sha256 = "8cd4a48067d935c844205e6b658da5bb293ccd97ef62c93c39bdaf55d1373e32"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/JuliaFormatter-ubuntu-latest-x64-1.8.tar.gz"

[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "0e7657bcc7439d497cea13f0fcc1d0f1f922e5c3"
lazy = true
os = "windows"

    [[JuliaSyntax.download]]
    sha256 = "cc351ec4c066af7a53db075a08abb1d331c4e67b5f74a659c62904b12aac6524"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/JuliaSyntax-windows-latest-x64-1.8.tar.gz"
[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "7b83bfa090ab4410b860bd7fb76701b570ee82cb"
lazy = true
os = "macos"

    [[JuliaSyntax.download]]
    sha256 = "64866f8a296ae4765433e5f450e2a00efabe8ecf1f348dec0d639b056d6a8876"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/JuliaSyntax-macOS-latest-x64-1.8.tar.gz"
[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "760ff5d1d1eb58a7de55443b9c5073f849343d08"
lazy = true
libc = "glibc"
os = "linux"

    [[JuliaSyntax.download]]
    sha256 = "010d6bdfcaf533c7557ed7211dd9d7b7634f17708c39b5a9846428485ed2ed19"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.8.0/JuliaSyntax-ubuntu-latest-x64-1.8.tar.gz"
