[[AlgebraOfGraphics]]
arch = "x86_64"
git-tree-sha1 = "c22312027b0d1a70c1e514a8c2d02b84aef6856a"
lazy = true
os = "windows"

    [[AlgebraOfGraphics.download]]
    sha256 = "c781638edbb0cba646322ca75de861cd2a2a71dc88008f883e29d229410bf3c5"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/AlgebraOfGraphics-windows-latest-x64-1.7.tar.gz"
[[AlgebraOfGraphics]]
arch = "x86_64"
git-tree-sha1 = "efedb4d235b414a77e2d3672c04fdc5e89bca81d"
lazy = true
os = "macos"

    [[AlgebraOfGraphics.download]]
    sha256 = "2b5a7d308178f209586d5bdadb4cf6ddda25ae0b44e77a36e6901c26174d3f3c"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/AlgebraOfGraphics-macOS-latest-x64-1.7.tar.gz"
[[AlgebraOfGraphics]]
arch = "x86_64"
git-tree-sha1 = "a0575c563adfc41a4e286f218595141e3335182e"
lazy = true
libc = "glibc"
os = "linux"

    [[AlgebraOfGraphics.download]]
    sha256 = "88478157cb43864fba6aec367e8575ca588868b7d666a4e7c9b624b0e7a00573"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/AlgebraOfGraphics-ubuntu-latest-x64-1.7.tar.gz"

[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "c85e40f5b2fc44f538f459d9cc8e5f3e4404b4ec"
lazy = true
os = "windows"

    [[CairoMakie.download]]
    sha256 = "ad16c951847ddc82101bc4dad4273fa9c815af0102bcb978215a7331f0ad08a9"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.2.0/CairoMakie-windows-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "c9f4666333eaa70f00865027e1a5fc55d0726fb3"
lazy = true
os = "macos"

    [[CairoMakie.download]]
    sha256 = "ee27b0546ee9db1e0560b88db1c391a32bfdc4eaf37f3123e5c4958284112f94"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.2.0/CairoMakie-macOS-latest-x64-1.7.tar.gz"
[[CairoMakie]]
arch = "x86_64"
git-tree-sha1 = "7fa2df6aadd76be0f34a8c65ecb29f85de5df458"
lazy = true
libc = "glibc"
os = "linux"

    [[CairoMakie.download]]
    sha256 = "e94f96161b0279ea1c7ebfac4e61756d91849bfa53df2911e007590570be0815"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.2.0/CairoMakie-ubuntu-latest-x64-1.7.tar.gz"

[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "4a9be73112d4327d7e27e6084fd6d67a08dca7b3"
lazy = true
os = "windows"

    [[DataFrames.download]]
    sha256 = "e7ef05ed10e8295eb01a5b6c36458d10c7b42657eacd4dac9148d66afcba0e08"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/DataFrames-windows-latest-x64-1.7.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "f6df036ca287f9506dff31bf10f088c3c7836232"
lazy = true
os = "macos"

    [[DataFrames.download]]
    sha256 = "af36ed21c49d6338daeff8df3a24943e3c9525cd5870637b02ca242583c1e9d5"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/DataFrames-macOS-latest-x64-1.7.tar.gz"
[[DataFrames]]
arch = "x86_64"
git-tree-sha1 = "ad4636bbbcf52ec7d035849cc92da6386aa70a03"
lazy = true
libc = "glibc"
os = "linux"

    [[DataFrames.download]]
    sha256 = "2b2cfd8bbb1aad1df7f04ea1d798f3b38e6c0eb6eba36b0d4a38313b878b04a9"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/DataFrames-ubuntu-latest-x64-1.7.tar.gz"

[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "a0c65a006ef5640908b55faddbba0f83d952ccda"
lazy = true
os = "windows"

    [[JuliaSyntax.download]]
    sha256 = "d0832b7c4725b86ac987eb4db3f38cffbc6cab233e20fb642a712f6a2b61875a"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/JuliaSyntax-windows-latest-x64-1.7.tar.gz"
[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "99ef4602b3ff7920cc1356f2d7ca0bd664f63a18"
lazy = true
os = "macos"

    [[JuliaSyntax.download]]
    sha256 = "ff8fb053fb79b941e04b36403b659361bcd09c66c09ffbbd7a787734f5a1be1f"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/JuliaSyntax-macOS-latest-x64-1.7.tar.gz"
[[JuliaSyntax]]
arch = "x86_64"
git-tree-sha1 = "1f32b1215ec0f3847cedbc8254288a60d205a476"
lazy = true
libc = "glibc"
os = "linux"

    [[JuliaSyntax.download]]
    sha256 = "ecfac026832cfef874f8062d162e4bef899b1da77d93a3756af3eb3de2f194e9"
    url = "https://github.com/MichaelHatherly/curated-system-images/releases/download/v0.3.0/JuliaSyntax-ubuntu-latest-x64-1.7.tar.gz"
