# Auto-generated by `artifacts/update.jl` script. Do not edit.

@ArtifactInstaller(
    artifact"AlgebraOfGraphics",
    artifact"DataFrames",
    artifact"JuliaFormatter",
    artifact"JuliaSyntax",
)
