name: Update Artifacts

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
          arch: x64

      - name: Instantiate artifacts environment
        run: julia --project=artifacts -e 'import Pkg; Pkg.instantiate()'

      - name: Get artifacts repo
        uses: actions/checkout@v3
        with:
          repository: 'MichaelHatherly/curated-system-images'
          path: 'curated-system-images'
          persist-credentials: false
          fetch-depth: 0

      - name: Update artifacts
        run: julia --project=artifacts artifacts/update.jl curated-system-images

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@171dd555b9ab6b18fa02519fdfacbb8bf671e1b4 # v4.0.4
        with:
          token: ${{  secrets.GITHUB_TOKEN }}
          commit-message: '🤖 Automatically update the Artifacts.toml'
          title: '🤖 Artifacts.toml Update'
          labels: automerge
          body: |-
            This pull request updates the `Artifacts.toml` file to the latest artifact versions.
          branch: bot/update/${{ github.ref }}
          delete-branch: true
          add-paths: |
            Artifacts.toml
            src/install.jl
